//常量

//获取直播列表
export const GET_USER_LIVE_LIST='GET_USER_LIVE_LIST';
export const GET_USER_LIVE_LIST_REQUEST='GET_USER_LIVE_LIST_REQUEST';
export const GET_USER_LIVE_LIST_FAILURE='GET_USER_LIVE_LIST_FAILURE';

export const GET_USER_LIVE_LIST_SUCCESS='GET_USER_LIVE_LIST_SUCCESS';
export const GET_ALL_LIST = 'GET_ALL_LIST';




export const GET_KEY_WORDS='GET_KEY_WORDS';

//sagas
export const GET_USER_LIVE_LIST_ASYNC='GET_USER_LIVE_LIST_ASYNC';
export const GET_KEY_WORDS_ASYNC='GET_KEY_WORDS_ASYNC';


export const SET_FROMPATH = 'SET_FROMPATH';
export const CHANGE_ALL_LIST = 'CHANGE_ALL_LIST';
export const CHANGE_LOADING = 'CHANGE_LOADING';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_HASMORE = 'CHANGE_HASMORE';